# Generated by Django 4.2.2 on 2023-08-08 19:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalAtVetClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_animal', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('other', 'Other')], max_length=20)),
                ('name_animal', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('medical_record', models.TextField()),
                ('vetclinic', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('vetclinic_city', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2)])),
                ('details_pet', models.TextField(blank=True, null=True)),
                ('current_bill', models.FloatField()),
                ('pictures', models.ImageField(upload_to='vetclinic/%Y/%m/%d/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AnimalVetClinic',
            },
        ),
        migrations.CreateModel(
            name='AnimalAdoptReadyCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)])),
                ('animal_type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('other', 'Other')], max_length=30)),
                ('location', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2)])),
                ('details', models.TextField()),
                ('other', models.TextField(blank=True)),
                ('picture', models.ImageField(upload_to='pets_for_adoption/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AnimalAdoptReady',
            },
        ),
    ]
