# Generated by Django 4.2.2 on 2023-07-04 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_alter_animaladoptreadycreate_animal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalAdoptSend',
            fields=[
                ('animaladoptreadycreate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='animals.animaladoptreadycreate')),
                ('place_to_live', models.CharField(max_length=50)),
                ('picture_of_place', models.ImageField(upload_to='owner_homes/%Y/%m/%d/')),
                ('other_pets', models.TextField()),
                ('other_details', models.TextField(blank=True, null=True)),
            ],
            bases=('animals.animaladoptreadycreate',),
        ),
        migrations.AlterField(
            model_name='animaladoptreadycreate',
            name='animal_type',
            field=models.CharField(choices=[('dog', 'Dog'), ('other', 'Other'), ('cat', 'Cat')], max_length=30),
        ),
    ]
