# Generated by Django 4.2.2 on 2023-07-06 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animals', '0006_alter_animaladoptreadycreate_animal_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaladoptreadycreate',
            name='animal_type',
            field=models.CharField(choices=[('dog', 'Dog'), ('other', 'Other'), ('cat', 'Cat')], max_length=30),
        ),
        migrations.CreateModel(
            name='AnimalAtVetClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_animal', models.CharField(choices=[('dog', 'Dog'), ('other', 'Other'), ('cat', 'Cat')], max_length=20)),
                ('name_animal', models.CharField(max_length=30)),
                ('medical_record', models.TextField()),
                ('vetclinic', models.CharField(max_length=50)),
                ('vetclinic_city', models.CharField(max_length=40)),
                ('details_pet', models.TextField(blank=True, null=True)),
                ('current_bill', models.FloatField()),
                ('pictures', models.ImageField(upload_to='vetclinic/%Y/%m/%d/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
