# Generated by Django 4.2.2 on 2023-07-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_alter_animaladoptreadycreate_animal_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaladoptreadycreate',
            name='animal_type',
            field=models.CharField(choices=[('other', 'Other'), ('cat', 'Cat'), ('dog', 'Dog')], max_length=30),
        ),
        migrations.AlterField(
            model_name='animalatvetclinic',
            name='type_animal',
            field=models.CharField(choices=[('other', 'Other'), ('cat', 'Cat'), ('dog', 'Dog')], max_length=20),
        ),
    ]
