# Generated by Django 4.2.2 on 2023-07-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_alter_animaladoptreadycreate_animal_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animaladoptreadycreate',
            options={'verbose_name_plural': 'AnimalAdoptReady'},
        ),
        migrations.AlterModelOptions(
            name='animalatvetclinic',
            options={'verbose_name_plural': 'AnimalVetClinic'},
        ),
        migrations.AlterField(
            model_name='animaladoptreadycreate',
            name='animal_type',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='animalatvetclinic',
            name='type_animal',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('other', 'Other')], max_length=20),
        ),
    ]
