# Generated by Django 4.2.2 on 2023-08-08 19:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareAnimalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('province', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('city', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('main_photo', models.ImageField(upload_to='help_animals/%Y/%m/%d/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ShareAnimal',
            },
        ),
        migrations.CreateModel(
            name='AdoptPetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pet', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('location', models.CharField(blank=True, max_length=50)),
                ('pet_story', models.TextField()),
                ('photo', models.ImageField(upload_to='happy_adopted/')),
                ('date_of_adoption', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AdoptPet',
            },
        ),
        migrations.CreateModel(
            name='AdoptionHomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('province', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2)])),
                ('city', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2)])),
                ('picture', models.ImageField(upload_to='adoption_homes/')),
                ('animal_type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('start_period', models.DateField()),
                ('end_period', models.DateField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AdoptionHome',
            },
        ),
    ]
