# Generated by Django 4.2.2 on 2023-07-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_adoptpetmodel_date_of_adoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptpetmodel',
            name='date_of_adoption',
            field=models.DateField(),
        ),
    ]
