# Generated by Django 4.2.2 on 2023-07-03 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0003_alter_adoptpetmodel_date_of_adoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionHomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('province', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('picture', models.ImageField(upload_to='adoption_homes/')),
                ('animal_type', models.CharField(choices=[('dog', 'Dog'), ('other', 'Other'), ('cat', 'Cat')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('start_period', models.DateField()),
                ('end_period', models.DateField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
