# Generated by Django 4.2.2 on 2023-07-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_itemshop_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemshop',
            name='main_photo',
            field=models.ImageField(upload_to='item_images/'),
        ),
    ]
