# Generated by Django 4.2.2 on 2023-07-02 12:55

from django.db import migrations, models
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_itemshop_main_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemshop',
            name='main_photo',
            field=models.ImageField(upload_to='item_images/', validators=[shop.validators.resize_file_image]),
        ),
    ]
