# Generated by Django 4.2.2 on 2023-07-08 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_itemshop_main_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemshop',
            options={'verbose_name_plural': 'ItemShop'},
        ),
    ]
